export const IsRegister = '/cellphone/existence/check'//查询手机号是否注册接口
export const Register = '/register/cellphone'//注册账号
export const SendVerificationCode = '/captcha/sent'//发送验证码
export const CaptchaVerify = '/captcha/verify'//检查验证码是否正确
export const RegisterCellPhone = '/register/cellphone'//注册账号/修改密码
export const InitProfile = '/activate/init/profile'//初始化昵称
export const LoginCellphone = '/login/cellphone'//手机号码登录
export const LoginStatus = '/login/status'//手机号码登录
export const GetLyric = '/lyric'//获取歌词
export const GetSongURL = '/song/url'//获取音乐url
export const RecentPlay = '/user/record'//获取用户最近播放记录
export const Banner = '/banner'//获取轮播图
export const Search = '/search'//搜索
export const SearchHotDetail = '/search/hot/detail'//热搜数据
export const DefaultSearchWord = '/search/default'//默认关键词
export const Artists = '/artists?id=6452'//歌手单曲信息
export const Album = '/artist/album'//歌手专辑信息
export const AlbumContent = '/artist'//歌手专辑内容
export const ArtistCategoryList = '/artist/list'//歌手分类列表
export const HotSong = '/artist/top/song'//歌手热门五十首单曲
export const SingerIntroduction = '/artist/desc'//歌手简介信息

